# 应用名称
spring:
  application:
    name: mall-tiny-01
  datasource:
    url: jdbc:mysql://121.37.9.58:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Spyczp.123
# 应用服务 WEB 访问端口
server:
  port: 8080
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml


